- hosts: checkpoint
  connection: httpapi

  tasks:
    
    - name: Create web server for sales
      cp_mgmt_host:
        name: "Sales Web Server"
        ip_address: 10.0.0.131
        
    - name: Create rule - Mobile Access for Internal FS
      cp_mgmt_access_rule:
        layer: "Data Center Layer"
        name: "Mobile Access for Internal FS"
        position: "1"
        source:
          - Sales
        destination:
          - FTP_Int
        vpn: 
          - RemoteAccess
        service: 
          - ftp 
        content:
          - "Document File"
          - "Archive File" 
        track:
          type: "Extended Log"         
        action: Accept
        
    - name: Create access rule - Only Finance department has access to reports
      cp_mgmt_access_rule:
        layer: "Data Center Layer"
        name: "Only Finance department has access to reports"
        position: "2"
        source:
          - "Finance User"
        destination:
          - ERP Server
        service: 
          - "Report Portal"
        track:
          type: "Extended Log"         
        action: Accept
        
    - name: Create access rule - Internal DNS Access
      cp_mgmt_access_rule:
        layer: "Data Center Layer"
        name: "Internal DNS Access"
        position: "3"
        source:
          - "DMZZone"
          - "InternalZone"
        destination:
          - DNS Server
        service: 
          - "dns"
        action: Accept
        
    - name: Create access rule - Customer Service Server
      cp_mgmt_access_rule:
        layer: "Data Center Layer"
        name: "Customer Service Server"
        position: "4"
        service: 
          - "Customer Service Portal"
        track:
          accounting: true
        action: Accept
        
    - name: Create access rule - Cleanup
      cp_mgmt_access_rule:
        layer: "Data Center Layer"
        name: "Cleanup"
        position: "5"
        
    - name: publish
      cp_mgmt_publish:
      register: publish_response
  
    - debug:
        var: publish_response
        