- hosts: checkpoint
  connection: httpapi

  tasks:
    - name: show network
      cp_network_facts:
        name: "Demo day object21"
        version: "1.5"
      register: show_network_response
        
    - debug:
        var: show_network_response